server:
  port: 8888
#  servlet:
#    context-path: /identity

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: EasyConnect
  datasource:
    url: jdbc:postgresql://localhost:5432/easy_connect
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    username: langxuatchieu@gmail.com
    host: smtp.gmail.com
    port: 587
    password: lzzq inof jkgv emxj
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
jwt:
  secret: Hay0Nhac1Nho2Ban3Than4Rang5Sap6Chuyen7Nha8Roi
  expiration: 1
  refreshable: 30

logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
#path:
#  url: